# vim: ft=rest

http://bitterjug.com
GET /wp-json/wp/v2/posts?page=2

http://bitterjug.com
GET /wp-json/wp/v2/posts


http://bitterjug.com
GET /wp-json/wp/v2/posts/1381

http://127.0.0.1:8000
GET /posts.json-page1

http://bitterjug.localhost
GET /wp-json/wp/v2/posts?page=2

http://bitterjug.localhost
GET /wp-json/wp/v2/posts?page=1

http://bitterjug.localhost
GET /wp-json/wp/v2/posts?slug=minimal-elm-program

http://bitterjug.localhost
GET /wp-json/wp/v2/posts?before=2017-02-08T21:01:52

http://bitterjug.localhost
GET /wp-json/wp/v2/posts?slug=waiting-on-the-platform

http://bitterjug.localhost
GET /wp-json/wp/v2/posts?before=2015-10-10T20:34:17

http://bitterjug.localhost
GET /wp-json/wp/v2/posts?order=asc&after=2015-10-10T20:34:17
